import '../assets/css/bootstrap-icons.css'
import '../assets/css/bold.css'
import '../assets/css/app.css'
import '../styles/global.css'
import type { AppProps } from 'next/app'
import 'bootstrap/dist/css/bootstrap.css';
import Head from 'next/head';
import Sidebar from '../components/sidebar/Sidebar';
import Footer from '../components/footer/Footer';
import Header from '../components/header/Header';

function MyApp({ Component, pageProps }: AppProps) {
  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="app">
        <Sidebar/>
        <div id="main">
          <Header/>
          <Component {...pageProps} />
          <Footer/>
        </div>
      </div>
    </>
  )
}

export default MyApp
